title: TechBrave 
subtitle: Tech website about software engineering, interview preparation, based on jekyll theme
author: TechBrave
email: techbrave19@gmail.com
url: "https://techbrave.github.io"
baseurl: ""
description: Tech website about software engineering, interview preparation, based on jekyll theme

github_username: techbrave 
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

google_analytics: UA-145885826-1
# disqus_shortname:

blog_theme: auto

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
